name: GitHub Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Compress Directories
        run: |
          cd artifact
          for dir in */; do
            dir_name=$(basename "$dir")
            new_dir_name="${dir_name}-$(basename ${{ github.ref }})"
            zip_file_name="${new_dir_name}.zip"
            mkdir ${new_dir_name}
            mkdir ${new_dir_name}/Mods
            find ${dir} -type f -name '*.dll' -exec cp {} ${new_dir_name}/Mods \;
            cd ${new_dir_name}
            zip -r ../${zip_file_name} Mods
            cd ..
          done
          cd ..
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: artifact/*.zip
          prerelease: contains(github.ref, 'beta')
